name: ServerDashboard

main: Baleine\ServerDashboard\Main

version: 2.1.2

api: 3.18.0

load: POSTWORLD

author: Baleine

commands:
  sd-toggle:
    usage: sd-toggle [on|off]
    permission: serverdashboard

permissions:
  serverdashboard:
    default: op